TEMPLATE = app
TARGET = 0510_Test01
QT += core \
    gui \
    opengl \
    sql
HEADERS += lib/GlobalMath.h \
    map/util/DatMapInfo.h \
    map/util/DatLatLon.h \
    map/util/DatToMapUtil.h \
    Radar/TestView.h \
    Radar/TestRect.h \
    Radar/ConnectLine.h \
    Radar/RaderItemInfo.h \
    Radar/RadarItem.h \
    Radar/MovingLine.h \
    Radar/RadarView.h \
    Radar/Radar.h \
    Radar/RadarWidget.h \
    Track/TrailComponent.h \
    Track/LabelComponent.h \
    Track/Airplane.h \
    Track/NodeTrack.h \
    ImgWidget/MAPINFO/UserMapInfo.h \
    MapWindow.h \
    ImgWidget/DRAWING/PosMng.h \
    sql/FixSqlGen.h \
    ImgWidget/DRAWING/ManualCoordDbProcess.h \
    sql/AirportSqlGen.h \
    sql/SqlGen.h \
    lib/UserInfo.h \
    lib/DbManager.h \
    lib/MyScrollBar.h \
    ImgWidget/DRAWING/SymbolSelector.h \
    ImgWidget/DRAWING/CTextItem.h \
    ImgWidget/DRAWING/InputText.h \
    ImgWidget/DRAWING/ManualCoord.h \
    ImgWidget/DRAWING/CArcItem.h \
    ImgWidget/DRAWING/CPolyLineItem.h \
    ImgWidget/DRAWING/CPolyGonItem.h \
    ImgWidget/ITEMS/MppItem.h \
    ImgWidget/ITEMS/LineItem.h \
    ImgWidget/LATLON/LatLonItem.h \
    ImgWidget/LATLON/usermathutil.h \
    ImgWidget/GeoData.h \
    ImgWidget/LATLON/NorthGreenichPoint.h \
    ImgWidget/LATLON/CalcAir.h \
    ImgWidget/LATLON/CenterCoord.h \
    ImgWidget/LATLON/LatLonConvert.h \
    ImgWidget/LATLON/MapConvertFunc.h \
    ImgWidget/OPENGL/GlWidgetWindow.h \
    ImgWidget/OPENGL/mainwindow.h \
    ImgWidget/OPENGL/const.h \
    ImgWidget/OPENGL/edge.h \
    ImgWidget/OPENGL/geomGraph.h \
    ImgWidget/OPENGL/gl2ps.h \
    ImgWidget/OPENGL/glwidget.h \
    ImgWidget/OPENGL/sphereCanvas.h \
    ImgWidget/OPENGL/vertex.h \
    lib/QGraphicsArcItem.h \
    lib/MyThread.h \
    lib/ProgressObj.h \
    ImgWidget/MAINMENU/SN/SNMenuWidget.h \
    ImgWidget/MAINMENU/MainMenuDlg.h \
    ImgWidget/DRAWING/CPixMap.h \
    ImgWidget/DRAWING/CGraphicItem.h \
    ImgWidget/ANGLE/AngleInfo.h \
    ImgWidget/DRAWING/CEllipseItem.h \
    ImgWidget/DRAWING/CLineItem.h \
    ImgWidget/DRAWING/CRectItem.h \
    ImgWidget/DRAWING/DrawingMng.h \
    ImgWidget/DRAWING/DrawingWidget.h \
    lib/ConvertPoint.h \
    lib/DataValidator.h \
    ImgWidget/COORDINATE/MapCoordDlg.h \
    ImgWidget/MAPINFO/LeftLayout.h \
    lib/LatLonDrawer.h \
    lib/Function.h \
    ImgWidget/MAPINFO/MapInfo.h \
    ImgWidget/MAPINFO/MyLineEdit.h \
    lib/LayerInfo.h \
    lib/LatLonMng.h \
    lib/LatLonToPixel.h \
    lib/WGS84_TMLib.h \
    lib/WGS84_TM.h \
    lib/GeoData.h \
    ImgWidget/BaseNode.h \
    ImgWidget/ENEMY/EMNode.h \
    ImgWidget/Weapon/WP_2.h \
    ImgWidget/DrawingExample_04.h \
    ImgWidget/DrawingScene.h \
    ImgWidget/ImgController.h \
    ImgWidget/Node.h \
    ImgWidget/NodeInfo.h \
    ImgWidget/Weapon/CommonWP.h \
    ImgWidget/Weapon/WP_1.h \
    ImgWidget/Window04.h
SOURCES += lib/GlobalMath.cpp \
    map/util/DatMapInfo.cpp \
    map/util/DatLatLon.cpp \
    map/util/DatToMapUtil.cpp \
    Radar/TestView.cpp \
    Radar/TestRect.cpp \
    Radar/ConnectLine.cpp \
    Radar/RaderItemInfo.cpp \
    Radar/RadarItem.cpp \
    Radar/MovingLine.cpp \
    Radar/RadarView.cpp \
    Radar/Radar.cpp \
    Radar/RadarWidget.cpp \
    Track/TrailComponent.cpp \
    Track/LabelComponent.cpp \
    Track/Airplane.cpp \
    Track/NodeTrack.cpp \
    ImgWidget/MAPINFO/UserMapInfo.cpp \
    MapWindow.cpp \
    ImgWidget/DRAWING/PosMng.cpp \
    sql/FixSqlGen.cpp \
    ImgWidget/DRAWING/ManualCoordDbProcess.cpp \
    sql/AirportSqlGen.cpp \
    sql/SqlGen.cpp \
    lib/UserInfo.cpp \
    lib/DbManager.cpp \
    lib/MyScrollBar.cpp \
    ImgWidget/DRAWING/SymbolSelector.cpp \
    ImgWidget/DRAWING/CTextItem.cpp \
    ImgWidget/DRAWING/InputText.cpp \
    ImgWidget/DRAWING/ManualCoord.cpp \
    ImgWidget/DRAWING/CArcItem.cpp \
    ImgWidget/DRAWING/CPolyLineItem.cpp \
    ImgWidget/DRAWING/CPolyGonItem.cpp \
    ImgWidget/ITEMS/MppItem.cpp \
    ImgWidget/ITEMS/LineItem.cpp \
    ImgWidget/LATLON/LatLonItem.cpp \
    ImgWidget/LATLON/NorthGreenichPoint.cpp \
    ImgWidget/LATLON/CalcAir.cpp \
    ImgWidget/LATLON/CenterCoord.cpp \
    ImgWidget/LATLON/LatLonConvert.cpp \
    ImgWidget/OPENGL/GlWidgetWindow.cpp \
    ImgWidget/OPENGL/mainwindow.cpp \
    ImgWidget/OPENGL/edge.cpp \
    ImgWidget/OPENGL/geomGraph.cpp \
    ImgWidget/OPENGL/gl2ps.c \
    ImgWidget/OPENGL/glwidget.cpp \
    ImgWidget/OPENGL/sphereCanvas.cpp \
    ImgWidget/OPENGL/vertex.cpp \
    lib/QGraphicsArcItem.cpp \
    lib/MyThread.cpp \
    lib/ProgressObj.cpp \
    ImgWidget/MAINMENU/SN/SNMenuWidget.cpp \
    ImgWidget/MAINMENU/MainMenuDlg.cpp \
    ImgWidget/DRAWING/CPixMap.cpp \
    ImgWidget/DRAWING/CGraphicItem.cpp \
    ImgWidget/ANGLE/AngleInfo.cpp \
    ImgWidget/DRAWING/CEllipseItem.cpp \
    ImgWidget/DRAWING/CLineItem.cpp \
    ImgWidget/DRAWING/CRectItem.cpp \
    ImgWidget/DRAWING/DrawingMng.cpp \
    ImgWidget/DRAWING/DrawingWidget.cpp \
    lib/ConvertPoint.cpp \
    lib/DataValidator.cpp \
    ImgWidget/COORDINATE/MapCoordDlg.cpp \
    ImgWidget/MAPINFO/LeftLayout.cpp \
    lib/LatLonDrawer.cpp \
    ImgWidget/MAPINFO/MapInfo.cpp \
    ImgWidget/MAPINFO/MyLineEdit.cpp \
    lib/LayerInfo.cpp \
    lib/LatLonMng.cpp \
    lib/LatLonToPixel.cpp \
    lib/WGS84_TM.cpp \
    ImgWidget/BaseNode.cpp \
    ImgWidget/ENEMY/EMNode.cpp \
    ImgWidget/Weapon/WP_2.cpp \
    ImgWidget/DrawingExample_04.cpp \
    ImgWidget/DrawingScene.cpp \
    ImgWidget/ImgController.cpp \
    ImgWidget/Node.cpp \
    ImgWidget/NodeInfo.cpp \
    ImgWidget/Weapon/CommonWP.cpp \
    ImgWidget/Weapon/WP_1.cpp \
    ImgWidget/Window04.cpp \
    main.cpp
FORMS += ImgWidget/NodeInfo.ui
RESOURCES += spherical.qrc
